name: Upload to S3 static bucket

on:
  push:
    branches:
      - aws-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Check for static website hosting bucket
        run: |
          if [ -z "$(aws s3 ls "${{ secrets.BUCKET_NAME }}" | grep "NoSuchBucket")" ]; then
            echo "Found bucket"
          else
            echo "Can't find the bucket"
            exit 1
          fi

      - name: Sync built to s3 bucket
        run: |
          aws s3 sync ./dist/ s3://$(echo ${{secrets.BUCKET_NAME}}) --delete
